package model;
// Generated Dec 19, 2018 1:33:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Current generated by hbm2java
 */
@Entity
@Table(name="current"
    ,catalog="asset"
)
public class Current  implements java.io.Serializable {


     private String ciName;
     private String serialNumber;
     private String macAddress;
     private String model;
     private String ipAddress;
     private Integer locationId;

    public Current() {
    }

	
    public Current(String ciName) {
        this.ciName = ciName;
    }
    public Current(String ciName, String serialNumber, String macAddress, String model, String ipAddress, Integer locationId) {
       this.ciName = ciName;
       this.serialNumber = serialNumber;
       this.macAddress = macAddress;
       this.model = model;
       this.ipAddress = ipAddress;
       this.locationId = locationId;
    }
   
     @Id 

    
    @Column(name="ciName", unique=true, nullable=false, length=45)
    public String getCiName() {
        return this.ciName;
    }
    
    public void setCiName(String ciName) {
        this.ciName = ciName;
    }

    
    @Column(name="serialNumber", length=45)
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    
    @Column(name="macAddress", length=45)
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    
    @Column(name="model", length=45)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="ipAddress", length=45)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    
    @Column(name="locationID")
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }




}


